clone:
  git:
    image: bash
    commands:
      - cd /home/0xmrtt
      - if [ -d Imaginer ]; then
      -   cd Imaginer
      -   git pull
      - else
      -   git clone https://git.exozy.me/Imaginer/Imaginer.git
      - fi

pipeline:
  build:
    image: fish
    secrets: [ access_token, codeberg_token ]
    commands:
      - nix-env -iA nixpkgs.flatpak-builder
      - fish_add_path ~/.nix-profile/bin
      - cd /home/0xmrtt/Imaginer
      - flatpak-builder --repo=repo --force-clean build build-aux/flatpak/page.codeberg.Imaginer.Imaginer.json
      - flatpak build-bundle repo imaginer.flatpak page.codeberg.Imaginer.Imaginer
      - ls -la
      - curl --user 0xmrtt:$ACCESS_TOKEN --upload-file imaginer.flatpak "https://git.exozy.me/api/packages/$CI_REPO_OWNER/generic/$CI_REPO_NAME/$CI_BUILD_NUMBER/imaginer.flatpak"
      - curl --user 0xmrtt:$CODEBERG_TOKEN --upload-file imaginer.flatpak "https://codeberg.org/api/packages/$CI_REPO_OWNER/generic/$CI_REPO_NAME/$CI_BUILD_NUMBER/imaginer.flatpak"

  translate:
    image: fish
    commands:
      - nix-env -iA nixpkgs.gettext
      - fish_add_path ~/.nix-profile/bin
      - cd /home/Imaginer
      - bash po/update-pot.sh
      - git add po/Imaginer.pot
      - git commit -m "Update"
      - git push origin main
    when:
      event: [manual]
